apiVersion: v1
kind: Secret
metadata:
  name: pythales-secret
  labels:
    app.kubernetes.io/name: pythales-hsm
    app.kubernetes.io/component: simulator
type: Opaque
stringData:
  # 32-hex character Local Master Key (LMK) string
  HSM_KEY: "deadbeefdeadbeefdeadbeefdeadbeef"
